artifact_uri: /Users/milanklanjsek/workspace/arepas/mlruns/310607781332450309/d2310fe96bdd43a095af536b9efc7289/artifacts
end_time: 1775606186802
entry_point_name: ''
experiment_id: '310607781332450309'
lifecycle_stage: active
run_id: d2310fe96bdd43a095af536b9efc7289
run_name: resnet50_data2_ph1-1_lr1e-04_bs32_ep8_legacy_single_roof_pat5
source_name: ''
source_type: 4
source_version: ''
start_time: 1775606186786
status: 3
tags: []
user_id: milanklanjsek
