artifact_location: /Users/milanklanjsek/workspace/arepas/mlruns/310607781332450309
creation_time: 1775606186670
experiment_id: '310607781332450309'
last_update_time: 1775606186670
lifecycle_stage: active
name: arepas
trace_location: null
workspace: default
